In [3]:
"""
Date: 3.9.21(Fri)
"""

'\nDate: 3.9.21(Fri)\n'

In [4]:
import pandas as pd
import numpy as np
from numpy.random import rand

In [5]:
class MultiVariateRegression():

  def __init__(self, learning_rate, num_iterations):
    self.learning_rate = learning_rate
    self.num_iterations = num_iterations

  def fit(self, X, Y):
    self.X = X
    self.Y = Y
    self.b = 0
    self.W = np.zeros(X.shape[1])

    for i in range(self.num_iterations):
      Y_predicted = self.predict(self.X)
      dW = - (2 *np.dot(self.X.T,(self.Y - Y_predicted) ) )/ self.X.shape[0]
      db = - 2 * np.sum( self.Y - Y_predicted ) / self.X.shape[0]
      self.W -= self.learning_rate * dW
      self.b -= self.learning_rate * db
  

  def predict(self, X):
    Y = np.dot(X, self.W)+self.b
    return Y


In [8]:
# Read Data
train_data = pd.read_csv('sample_data/california_housing_test.csv')
test_data = pd.read_csv('sample_data/california_housing_test.csv')

# Remove Null Values
train_data.dropna(inplace = True)
test_data.dropna(inplace= True)


X_train = train_data.iloc[:,:-1].values
Y_train = train_data.iloc[:,1].values

X_test = test_data.iloc[:,:-1].values
Y_test = test_data.iloc[:,1].values

In [9]:
X_train

array([[-122.05  ,   37.37  ,   27.    , ..., 1537.    ,  606.    ,
           6.6085],
       [-118.3   ,   34.26  ,   43.    , ...,  809.    ,  277.    ,
           3.599 ],
       [-117.81  ,   33.78  ,   27.    , ..., 1484.    ,  495.    ,
           5.7934],
       ...,
       [-119.7   ,   36.3   ,   10.    , ...,  693.    ,  220.    ,
           2.2895],
       [-117.12  ,   34.1   ,   40.    , ...,   46.    ,   14.    ,
           3.2708],
       [-119.63  ,   34.42  ,   42.    , ...,  753.    ,  260.    ,
           8.5608]])

In [11]:
#model = LinearRegression(0.001,   15000)
model = MultiVariateRegression(0.000000001,   100)
#model.fit(X_train, Y_train)
model.fit(X_train, Y_train)

In [12]:
Y_predicted = model.predict(X_test)


In [13]:
Y_predicted

array([29.10066103, 12.22083973, 26.90702824, ...,  8.46140599,
        0.8098974 , 13.38862268])

In [14]:
Y_test

array([37.37, 34.26, 33.78, ..., 36.3 , 34.1 , 34.42])

In [15]:

mean_square_error = sum([(y-y_predicted)**2 for y, y_predicted in zip(Y_test, Y_predicted)])/len(Y_predicted)

In [16]:
mean_square_error

488.1781786167659